variant = "loose"

[[issues]]
file = "src/RouteParser.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/RouteParser.php"
code = "kan-defect"
message = "Class has a high kan defect score (1.7000000000000002)."
count = 1

[[issues]]
file = "src/RouteParser.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/RouteParser.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "src/RouteParser.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/RouteParser.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 2

[[issues]]
file = "src/Trait/RequestTrait.php"
code = "no-redundant-use"
message = "Unused import: `Constant`."
count = 1

[[issues]]
file = "tests/src/AbstractTestCase.php"
code = "no-redundant-method-override"
message = "Redundant method override."
count = 2

[[issues]]
file = "tests/src/Cache/RouteCacheTest.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "tests/src/Helper/MockContainer.php"
code = "braced-string-interpolation"
message = "Unbraced variable in string interpolation."
count = 2

[[issues]]
file = "tests/src/Helper/MockContainer.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "tests/src/Helper/MockContainer.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "tests/src/Helper/MockContainer.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "tests/src/Helper/MockContainer.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "tests/src/Router/ControllerFinderTest.php"
code = "explicit-octal"
message = "Use explicit octal numeral notation."
count = 1

[[issues]]
file = "tests/src/Router/RouterTest.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 1

[[issues]]
file = "tests/src/Router/RouterTest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1
